#-*-encoding:utf-8 -*-
"""
@version:1
@author:刘雅
@file:Bl_value.py
@time:2019/1/1616:03
"""
# 获取后台的变量名
def get_Bak_name():
    return "bakSess"
# 获取前台loginSess的变量名
def get_login_name():
    return "loginSess"
# 获取memberId的值
def get_memberId():
    return "memberId"
# 获取global_topicId的变量名
def get_global_topicId():
    return "global_topicId"
# 获取后台的标识字段
def get_Identifi_file_account_login():
    return "account_login"
# 获取后台的登录账户
def get_Identifi_file_email():
    return "email"
# 获取后台的登录密码
def get_Identifi_file_password():
    return "password"
# 获取前台登录的标识字段
def get_member_login():
    return "member_login"
#获取前台登录密码
def get_member_login_password():
    return "member_password"
# 获取tenantId的标识字段
def get_dentifi_file_tenantId():
    return "tenantId"
# 获取nodeId的标识字段
def get_nodeId():
    return "nodeId"
# 获取schemaId的标识字段
def get_dentifi_file_schemaId():
    return "schemaId"
# 获取memberFormId的标识字段
def get_dentifi_file_memberFormId():
    return "memberFormId"
# 获取memberSchemaId的标识字段
def get_dentifi_file_memberSchemaId():
    return "memberSchemaId"
# 获取unique的标识字段
def get_dentifi_file_unique():
    return "unique"
# 获取topicId的标识字段
def get_topicId():
    return "topicId"
# 获取微讨论子版Id的标识字段
def get_sectionId():
    return "section_create"
# 获取创建线下会
def get_create_seminarId():
    return "seminar_create"
# 获取memberFormId
def get_memberFormId():
    return "memberFormId"
# 获取memberFormName
def get_memberFormName():
    return "memberFormName"
# 获取seminarId值
def get_seminarId():
    return "seminarId"
# 获取instanceId值
def get_seminarId_instanceId():
    return "seminarId_instanceId"
# 获取passageId值
def get_passageId():
    return "passageId"
# 获取luckyDrawId值
def get_luckyDrawId():
    return "luckyDrawId"
def get_luckDrawsetItem():
    return "luckDrawsetItems"
# 获取signingPointId值
def get_signingPointId():
    return "signingPointId"
# 获取签到大屏模板id
def get_bigScreen_templateId():
    return "bigScreen_templateId"
# 获取大屏conigId
def get_bigScreen_configId():
    return "bigScreen_configId"
# 获取多次签到点id
def get_signingPointIds():
    return "signingPointIds"
# 获取大屏id
def get_bigScreenId():
    return "bigScreenId"
# 获取线下会设置大屏url
def semainr_setModule():
    return "seminar_setModule"
# 获取productLine
def get_productLine():
    return "productLine"
# 获取线上会id
def get_webinar_instanceId():
    return "webinar_instanceId"
# 获取线上会webinarId
def get_webinarId():
    return "webinarId"
# 获取线上会的instanceId
def get_webinarId_instanceId():
    return "webinarId_instanceId"
# 获取customFormId
def get_customFormId():
    return "register_getList"
# 获取customFormId
def get_customFormId_bl():
    return "customFormId"
# 开启线下会报名表单
def get_open_offline_meetingthe_form():
    return "customForm_start"
# 获取问卷ID,questionid—wj
def get_questionid():
    return "questionid_wj"
# 获取guestId
def get_guestId():
    return "guestId"
# 获取productLineId
def get_productLineId():
    return "productLineId"
# 获取线上会点播id
def webinar_instanceId_DianBo():
    return "webinar_instanceId_DianBo"
# 获取线上会点播webinarId_DianBo
def webinarId_DianBo():
    return "webinarId_DianBo"
# 线下会日程创建获取agendaId
def get_agendaId():
    return "agendaId"
# 获取栏目ID,categoryId
def get_categoryId():
    return "categoryId"
# 获取文件夹id，fileId
def get_rootFileId():
    return "rootFileId"
# 获取文件夹id，createFolderiD
def get_createFolderiD():
    return "createFolderiD"
# 获取FolderId值
def get_FolderId():
    return "FolderId"
# 获取pollId值
def get_pollId():
    return "pollId"
# 获取taskId
def get_taskId():
    return "taskId"
# 获取邮件内容值
def get_task_updateContent():
    return "task_updateContent"
# 获取自定义通用表单id
def get_registerFormId():
    return "registerFormId"
# 获取随机试卷的标识字段
def get_questionid_sjsj():
    return "questionid_sjsj"
# 开启线下会报名表单
def get_seminar_customForm_start():
    return "seminar_customForm_start"
# 线下会报名接口
def get_customForm_action():
    return "customForm_action"
# 设置参会人为普通参会人员第一步
def get_ptcontact_one():
    return "contact_isSignUp"
# 获取参会人员信息,contactId
def get_contactId():
    return "contactId"
def get_contactId_set():
    return "contract_set"
# 设置问卷选项,questionarywj_setItems
def get_questionarywj_setItems():
    return "questionarywj_setItems"
# 获取问卷选项item值,questionarywj_get
def get_questionarywj_get():
    return "questionarywj_get"
# 获取问卷item值
def get_questionid_item():
    return "questionid_item"
# 获取试卷id，questionid—sj
def get_questionid_sj():
    return "questionid_sj"
# 获取试卷id，questionid—sj
def get_questionary_update():
    return "questionary_update"
# 获取线下会分会场iD
def get_subSeminarId():
    return "subSeminarId"
# 获取试卷添加题目标识字段
def get_questionarysj_setItems():
    return "questionarysj_setItems"
# 获取articleCategoryId
def get_articleCategoryId():
    return "articleCategoryId"
# 获取articleID
def get_articleId():
    return "articleId"

# 获取dicID和dicname标识字段
def get_dicId_and_dicname():
    return "dicId"
# 获取dicID和dicname标识字段
def get_dicname():
    return "dicname"
# 获取门禁多次签到接口的通道值
def get_passagesId():
    return "passagesId"
# 文件夹内上传图片
def get_file_upload():
    return "file_upload"
def get_file_mappingId():
    return "mappingId"
# 获取微讨论下面的帖子id-postId的接口
def get_forum_post_postId():
    return "forum_post_postId"
# 获取id-postId的接口
def get_postId():
    return "postId"
# 获取id-PLQID的接口
def get_PLQID():
    return "PLQId"
# 文件夹内获取上传图片的文件id
def get_file_create():
    return "file_create"
def get_fileId():
    return "fileId"
# 获取留言板的主贴id
def get_LYBZTId():
    return "LYBZTId"
# 获取只有姓名和手机的表单id
def get_customForm_nameand_phone():
    return "customForm_nameand_phone"
# 获取表单ID
def get_customFormid_nameand_phone():
    return"customFormid_nameand_phone"
# 获取自定义注册表单id
def get_zdyresterFormId():
    return "zdyresterFormId"
# 获取标签属性值
def get_tag_field_getList():
    return "tag_field_getList"
# 获取tagSchemaId
def get_tagSchemaId():
    return "tagSchemaId"
# 获取tagFieldId
def get_tagFieldId():
    return "tagFieldId"
# 获取fieldName
def get_fieldName():
    return "fieldName"
# 获取displayName
def get_displayName():
    return "displayName"
# 获取tagId
def get_tagId():
    return "tagId"
# 获取创建线上会视频url
def get_create_video():
    return "create_video"
# 获取往线上会上传视频的url
def get_input_video():
    return "input_video"
def get_videoId():
    return "videoId"
def get_webinar_BMFormId():
    return "webinar_BMFormId"
def get_schemaId():
    return "schemaId"
def get_webinar_question_wj():
    return "webinar_question_wj"